image: python:3.6
build:
  script:
    - python setup.py build
  
dist:
  script:
    - python setup.py sdist

validate:
  script:
    - pip install pytest
    - pip install lxml
    - python setup.py build
    - python setup.py test