#!/usr/bin/python
""" Main script to run any Elements-based project """

from Euclid.Script import Script
from Euclid import Run

import logging

import sys
import os

class ERunScript(Script):
    _version = __version__
    _description = __doc__
    
#-----------------------------------------------------------------------------------
# Option definition

    def defineOpts(self):
        """ define commandline options """
        parser = self.parser

#-----------------------------------------------------------------------------------
# Main definition

    def main(self):
        opts = self.options
        args = self.args
        log = logging.getLogger()
        
        if len(args) < 2 :
            log.fatal("Not enough arguments")
            exit(1)
            
        project = args[0]
        version = "latest"
        
        if len(args) == 2 : 
            command = args[1]
        else :
            version = args[1]
            command = args[2]
            
        
        retcode = Run.execute(project, command, version)

        return retcode

if __name__ == '__main__':
    sys.exit(ERunScript(usage="%prog [options] project [version] cmd").run())

